### ISSUE TITLE
todo 22.3.2024

### ISSUE THREAD

**Issue by borbware** [borbware/todo#14]
- [ ] conditionals 5 ja 5 variant-ratkasu väärin
- [ ] disclaimeri 
- [ ] vs code prettier extension: format on save puuttu
- [ ] array.split ei mainittu
- [ ] eslint config ts vs js!!!!
- [ ] html hyvät tavat, ei kiirettä
- [ ] https://www.totaltypescript.com/cannot-redeclare-block-scoped-variable
- [ ] https://web.archive.org/web/20180609155906/http://fullstack-developer.academy/cannot-redeclare-block-scoped-variable-name/
